service: wetterheld-wrapper
frameworkVersion: "3"

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  timeout: 30
  region: eu-central-1
  apiGateway:
    shouldStartNameWithService: true

functions:
  getPrice:
    handler: handler.getPrice
    events:
      - httpApi:
          path: /getPrice
          method: get
